-- Student login support for Chalo Padhaye.
-- Run after 005_cbse_support.sql.
-- Students use normal Supabase Auth accounts and claim one child profile with
-- a short-lived invite code generated by the parent. No service-role key is used.

create extension if not exists pgcrypto;

alter table students
  add column if not exists student_user_id uuid references auth.users(id) on delete set null;

create unique index if not exists students_student_user_id_uidx
  on students(student_user_id)
  where student_user_id is not null;

create table if not exists student_invites (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  code_hash text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists student_invites_student_idx
  on student_invites(student_id, expires_at desc);

alter table student_invites enable row level security;
revoke all on student_invites from anon, authenticated;

create or replace function public.create_student_invite(p_student_id uuid)
returns table(invite_code text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_code text;
  v_expires timestamptz := now() + interval '24 hours';
begin
  if auth.uid() is null then
    raise exception 'Parent login required';
  end if;

  if not exists (
    select 1 from students s
    where s.id = p_student_id
      and s.parent_id = auth.uid()
  ) then
    raise exception 'Student is not available to this parent';
  end if;

  delete from student_invites
  where student_id = p_student_id
    and used_at is null;

  v_code := upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 8));

  insert into student_invites(student_id, code_hash, created_by, expires_at)
  values (
    p_student_id,
    encode(digest(v_code, 'sha256'), 'hex'),
    auth.uid(),
    v_expires
  );

  return query select v_code, v_expires;
end;
$$;

revoke all on function public.create_student_invite(uuid) from public;
grant execute on function public.create_student_invite(uuid) to authenticated;

create or replace function public.claim_student_invite(p_code text)
returns table(student_id uuid, full_name text, grade integer, board text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_invite student_invites%rowtype;
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Student login required';
  end if;

  select * into v_invite
  from student_invites i
  where i.code_hash = encode(digest(upper(trim(p_code)), 'sha256'), 'hex')
    and i.used_at is null
    and i.expires_at > now()
  order by i.created_at desc
  limit 1
  for update;

  if v_invite.id is null then
    raise exception 'Invite code is invalid or expired';
  end if;

  if exists (
    select 1 from students s
    where s.student_user_id = v_uid
      and s.id <> v_invite.student_id
  ) then
    raise exception 'This student account is already linked to another profile';
  end if;

  update students
  set student_user_id = v_uid
  where id = v_invite.student_id;

  update student_invites
  set used_at = now()
  where id = v_invite.id;

  return query
    select s.id, s.full_name, s.grade, s.board
    from students s
    where s.id = v_invite.student_id;
end;
$$;

revoke all on function public.claim_student_invite(text) from public;
grant execute on function public.claim_student_invite(text) to authenticated;

-- Students may read only their own profile. Parent create/update/delete stays parent-only.
drop policy if exists "parents read own students" on students;
create policy "parents or student read own profile"
on students for select
to authenticated
using (parent_id = auth.uid() or student_user_id = auth.uid());

-- Core learning records: either the parent or the linked student may use them.
drop policy if exists "parents manage own progress" on student_progress;
create policy "family manage own progress"
on student_progress for all
to authenticated
using (
  exists (
    select 1 from students s
    where s.id = student_progress.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1 from students s
    where s.id = student_progress.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
);

drop policy if exists "parents manage own sessions" on tutor_sessions;
create policy "family manage own sessions"
on tutor_sessions for all
to authenticated
using (
  exists (
    select 1 from students s
    where s.id = tutor_sessions.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1 from students s
    where s.id = tutor_sessions.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
);

drop policy if exists "parents manage own messages" on tutor_messages;
create policy "family manage own messages"
on tutor_messages for all
to authenticated
using (
  exists (
    select 1
    from tutor_sessions ts
    join students s on s.id = ts.student_id
    where ts.id = tutor_messages.session_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1
    from tutor_sessions ts
    join students s on s.id = ts.student_id
    where ts.id = tutor_messages.session_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
);

-- Structured lesson mastery.
drop policy if exists "parents manage own lesson progress" on lesson_progress;
create policy "family manage own lesson progress"
on lesson_progress for all
to authenticated
using (
  exists (
    select 1 from students s
    where s.id = lesson_progress.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1 from students s
    where s.id = lesson_progress.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
);

drop policy if exists "parents manage own lesson steps" on lesson_step_records;
create policy "family manage own lesson steps"
on lesson_step_records for all
to authenticated
using (
  exists (
    select 1 from students s
    where s.id = lesson_step_records.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1 from students s
    where s.id = lesson_step_records.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
);

drop policy if exists "parents manage own lesson tests" on lesson_test_attempts;
create policy "family manage own lesson tests"
on lesson_test_attempts for all
to authenticated
using (
  exists (
    select 1 from students s
    where s.id = lesson_test_attempts.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
)
with check (
  exists (
    select 1 from students s
    where s.id = lesson_test_attempts.student_id
      and (s.parent_id = auth.uid() or s.student_user_id = auth.uid())
  )
);

-- Students can see parent-created assignments/portfolio records, but cannot edit them directly.
drop policy if exists "students read own homeschool records" on homeschool_records;
create policy "students read own homeschool records"
on homeschool_records for select
to authenticated
using (
  exists (
    select 1 from students s
    where s.id = homeschool_records.student_id
      and s.student_user_id = auth.uid()
  )
);
