create table if not exists students (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  grade int not null check (grade in (3,5)),
  medium text not null default 'English',
  created_at timestamptz not null default now()
);

create table if not exists learning_sessions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  subject text,
  chapter text,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references students(id) on delete cascade,
  subject text not null,
  chapter text not null,
  score numeric,
  attempts int not null default 0,
  updated_at timestamptz not null default now(),
  unique(student_id, subject, chapter)
);
