let CFG={},CATALOG={},accessToken='',refreshToken='',students=[],sessionId=null,lastTutorText='',voiceMuted=false,voiceBusy=false,voiceGeneration=0,chatBusy=false,curriculum='maharashtra',activity='teach',lastDashboard=null,lastPortfolio=[],lessonsCache=[],activeLesson=null,testState=null,lastStudentState='neutral',lastDelivery='normal';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const savedSpeed=localStorage.getItem('cp_voice_speed');if(savedSpeed)$('#speed').value=savedSpeed;$('#speedVal').textContent=$('#speed').value+'×';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2600)}
function add(t,c){const d=document.createElement('div');d.className='msg '+c;d[c==='bot'?'innerHTML':'textContent']=c==='bot'?'<p>'+esc(t).replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>')+'</p>':t;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight}
function current(){return students.find(x=>x.id===$('#student').value)}
function storeSession(j){accessToken=j.access_token||accessToken;refreshToken=j.refresh_token||refreshToken;if(accessToken)sessionStorage.setItem('cp_token',accessToken);if(refreshToken)sessionStorage.setItem('cp_refresh',refreshToken)}
async function refreshSession(){if(!refreshToken)return false;try{const r=await fetch(`${CFG.supabase_url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:CFG.supabase_anon_key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const j=await r.json();if(!r.ok)return false;storeSession(j);return true}catch{return false}}
async function authFetch(url,opts={}){let o={...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${accessToken}`}};let r=await fetch(url,o);if(r.status===401&&await refreshSession()){o={...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${accessToken}`}};r=await fetch(url,o)}return r}
function preferredSchoolCurriculum(){const p=current();return p&&/cbse/i.test(p.board||'')?'cbse':'maharashtra'}
function subjectList(c=curriculum){const p=current();return p?((CATALOG[c]||{})[String(p.grade)]||[]):[]}
function subjectLabel(id,c=curriculum,grade=(current()||{}).grade){return ((((CATALOG[c]||{})[String(grade)]||[]).find(x=>x.id===id)||{}).label)||id||'General'}
function parseSubject(raw){if((raw||'').includes(':')){const [c,...r]=raw.split(':');return{curriculum:c,subject:r.join(':')}}return{curriculum:'maharashtra',subject:raw||''}}
let browserVoices=[];
function refreshVoices(){if(!('speechSynthesis'in window))return;browserVoices=window.speechSynthesis.getVoices()||[];const old=localStorage.getItem('cp_voice_name')||$('#voiceChoice').value;$('#voiceChoice').innerHTML='';const english=browserVoices.filter(v=>/^en/i.test(v.lang));const pool=english.length?english:browserVoices;pool.forEach(v=>$('#voiceChoice').add(new Option(`${v.name} (${v.lang})`,v.name)));let choice=pool.find(v=>v.name===old)||pool.find(v=>/^en-IN/i.test(v.lang))||pool.find(v=>/^en-GB/i.test(v.lang))||pool.find(v=>/^en-US/i.test(v.lang))||pool[0];if(choice)$('#voiceChoice').value=choice.name}
function chosenVoice(){const name=$('#voiceChoice').value;return browserVoices.find(v=>v.name===name)||browserVoices.find(v=>/^en-IN/i.test(v.lang))||browserVoices.find(v=>/^en/i.test(v.lang))||browserVoices[0]||null}
function stopVoice(status=''){voiceGeneration++;if('speechSynthesis'in window)window.speechSynthesis.cancel();voiceBusy=false;$('#stopVoice').disabled=true;$('#replay').disabled=!lastTutorText;if(status)$('#voiceStatus').textContent=status}
function spokenChunks(text){const clean=String(text||'').replace(/[#*_`]+/g,'').replace(/\s+/g,' ').trim();if(!clean)return[];return clean.split(/(?<=[.!?।])\s+/).filter(Boolean).slice(0,8)}
function effectiveRate(state='neutral',delivery='normal'){const p=current(),base=Number($('#speed').value||.82);let r=base;if((p||{}).grade<=1)r-=.06;else if((p||{}).grade<=3)r-=.03;else if((p||{}).grade>=9)r+=.02;if(['uncertain','struggling','frustrated'].includes(state))r-=.06;if(['slow','gentle'].includes(delivery))r-=.04;return Math.max(.65,Math.min(.95,r))}
function speakTutor(text,state='neutral',delivery='normal',force=false){if((voiceMuted&&!force)||!text||!('speechSynthesis'in window))return;stopVoice();const generation=voiceGeneration,chunks=spokenChunks(text);if(!chunks.length)return;voiceBusy=true;$('#stopVoice').disabled=false;$('#replay').disabled=true;const voice=chosenVoice(),p=current(),rate=effectiveRate(state,delivery),pitch=(p&&p.grade<=3)?1.04:1.0;let i=0;const next=()=>{if(generation!==voiceGeneration)return;if(i>=chunks.length){voiceBusy=false;$('#stopVoice').disabled=true;$('#replay').disabled=!lastTutorText;$('#voiceStatus').textContent='Your turn.';$('#q').focus();return}const chunk=chunks[i++],u=new SpeechSynthesisUtterance(chunk);if(voice){u.voice=voice;u.lang=voice.lang}u.rate=rate;u.pitch=pitch;u.volume=1;u.onstart=()=>{if(generation===voiceGeneration)$('#voiceStatus').textContent=`Tutor speaking slowly… ${i}/${chunks.length}`};u.onend=()=>{if(generation!==voiceGeneration)return;const pause=/\?$/.test(chunk)?360:190;setTimeout(next,pause)};u.onerror=()=>{if(generation!==voiceGeneration)return;voiceBusy=false;$('#stopVoice').disabled=true;$('#voiceStatus').textContent='Browser voice stopped.'};window.speechSynthesis.speak(u)};setTimeout(next,120)}
