<?php
declare(strict_types=1);
require_once __DIR__.'/learning.php';

function lesson_plan(): array { static $p=null; if($p===null)$p=json_decode((string)file_get_contents(dirname(__DIR__).'/data/lesson_plans.json'),true)?:[]; return $p; }
function lesson_slug(string $v): string { $s=trim(preg_replace('/[^a-z0-9]+/','-',strtolower($v))??'','-');return substr($s?:'lesson',0,42); }
function lesson_defs(string $c,int $g,string $subject): array { $titles=lesson_plan()['curricula'][$c][(string)$g][$subject]??[];$out=[];$i=1;foreach($titles as $t){$out[]=['id'=>sprintf('%s-%02d-%s',$subject,$i,lesson_slug((string)$t)),'order'=>$i,'title'=>(string)$t];$i++;}return $out; }
function lesson_steps_template(): array { return lesson_plan()['mastery']['steps']??[]; }
function lesson_pass_score(): int { return (int)(lesson_plan()['mastery']['pass_score']??70); }
function progress_rows(string $sid,string $c,string $subject): array {$q=db()->prepare('SELECT * FROM lesson_progress WHERE student_id=? AND curriculum=? AND subject=? ORDER BY lesson_order');$q->execute([$sid,$c,$subject]);return $q->fetchAll();}
function step_rows(string $sid,array $pids): array {if(!$pids)return[];$marks=implode(',',array_fill(0,count($pids),'?'));$q=db()->prepare("SELECT * FROM lesson_step_records WHERE student_id=? AND lesson_progress_id IN ($marks) ORDER BY step_order");$q->execute(array_merge([$sid],$pids));return $q->fetchAll();}
function lesson_definition(array $student,string $c,string $subject,string $lid): array {$defs=lesson_defs($c,(int)$student['grade'],$subject);foreach($defs as $d)if($d['id']===$lid)return[$d,$defs];json_response(['error'=>'Lesson is not defined for this student and subject'],404);}
function can_open(int $order,array $defs,array $by): bool {if($order<=1)return true;$prev=$defs[$order-2]??null;return $prev && (($by[$prev['id']]['status']??'')==='mastered');}
function get_progress(string $sid,string $c,string $subject,string $lid): ?array {$q=db()->prepare('SELECT * FROM lesson_progress WHERE student_id=? AND curriculum=? AND subject=? AND lesson_id=? LIMIT 1');$q->execute([$sid,$c,$subject,$lid]);$r=$q->fetch();return$r?:null;}
function ensure_steps(string $sid,array $p): array {$templates=lesson_steps_template();$q=db()->prepare('SELECT * FROM lesson_step_records WHERE lesson_progress_id=? ORDER BY step_order');$q->execute([$p['id']]);$rows=$q->fetchAll();$by=[];foreach($rows as $r)$by[$r['step_id']]=$r;$current=$p['current_step']?:'learn';$orders=[];foreach($templates as $t)$orders[$t['id']]=(int)$t['order'];$co=$orders[$current]??1;foreach($templates as $t){if(isset($by[$t['id']]))continue;$status=$p['status']==='mastered'?'completed':((int)$t['order']<$co?'completed':((int)$t['order']===$co?'available':'locked'));$id=uuid_v4();db()->prepare('INSERT INTO lesson_step_records(id,lesson_progress_id,student_id,step_id,step_order,step_title,status,completed_at) VALUES(?,?,?,?,?,?,?,?)')->execute([$id,$p['id'],$sid,$t['id'],(int)$t['order'],$t['title'],$status,$status==='completed'?gmdate('Y-m-d H:i:s'):null]);}$q->execute([$p['id']]);return$q->fetchAll();}
function ensure_progress(array $student,string $c,string $subject,array $lesson,array $defs): array {$p=get_progress($student['id'],$c,$subject,$lesson['id']);if($p){ensure_steps($student['id'],$p);return$p;}$rows=progress_rows($student['id'],$c,$subject);$by=[];foreach($rows as $r)$by[$r['lesson_id']]=$r;if(!can_open((int)$lesson['order'],$defs,$by))json_response(['error'=>'Complete the previous chapter test before opening this lesson'],403);$id=uuid_v4();db()->prepare("INSERT INTO lesson_progress(id,student_id,curriculum,subject,lesson_id,lesson_order,lesson_title,status,current_step,percent_complete,started_at) VALUES(?,?,?,?,?,?,?,'in_progress','learn',0,UTC_TIMESTAMP())")->execute([$id,$student['id'],$c,$subject,$lesson['id'],$lesson['order'],$lesson['title']]);$p=get_progress($student['id'],$c,$subject,$lesson['id']);ensure_steps($student['id'],$p);return$p;}
function lessons_list(array $student,string $c,string $subject): array {$defs=lesson_defs($c,(int)$student['grade'],$subject);$rows=progress_rows($student['id'],$c,$subject);$by=[];foreach($rows as$r)$by[$r['lesson_id']]=$r;$steps=step_rows($student['id'],array_column($rows,'id'));$sb=[];foreach($steps as$s)$sb[$s['lesson_progress_id']][]=$s;$result=[];foreach($defs as$d){$r=$by[$d['id']]??null;$status=$r['status']??(can_open((int)$d['order'],$defs,$by)?'available':'locked');$rs=$r?($sb[$r['id']]??[]):array_map(fn($t)=>$t+['status'=>((int)$t['order']===1&&$status==='available')?'available':'locked','attempts'=>0,'correct_count'=>0,'score'=>null],lesson_steps_template());$result[]=$d+['status'=>$status,'percent_complete'=>(int)($r['percent_complete']??0),'test_score'=>$r['test_score']??null,'test_attempts'=>(int)($r['test_attempts']??0),'current_step'=>$r['current_step']??($status==='available'?'learn':null),'steps'=>$rs];}$mastered=count(array_filter($result,fn($x)=>$x['status']==='mastered'));return['student'=>$student,'curriculum'=>$c,'subject'=>$subject,'storage_available'=>true,'migration'=>null,'pass_score'=>lesson_pass_score(),'mastered'=>$mastered,'total'=>count($result),'percent'=>$result?(int)round($mastered*100/count($result)):0,'lessons'=>$result];}
