<?php
declare(strict_types=1);
require_once __DIR__.'/lessons.php';

function http_json(string $url,array $headers,array $body,int $timeout=45): array {
    $ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>$headers,CURLOPT_POSTFIELDS=>json_encode($body),CURLOPT_TIMEOUT=>$timeout]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false||$status<200||$status>=300)throw new RuntimeException("Upstream request failed: {$status} {$err}");$j=json_decode($raw,true);if(!is_array($j))throw new RuntimeException('Invalid upstream JSON');return$j;
}
function groq_tutor(array $student,array $b,array $history=[]): array {
    $key=env_value('GROQ_API_KEY');if(!$key)json_response(['error'=>'Groq is not configured'],503);$model=env_value('GROQ_MODEL','openai/gpt-oss-20b');
    $system="You are Chalo Padhaye, a patient educational tutor. Student: {$student['full_name']}, grade {$student['grade']}. Curriculum: ".($b['curriculum']??'maharashtra').". Subject: ".($b['subject']??'general').". Activity: ".($b['activity']??'teach').". Teach one small step at a time. For a wrong answer, give a hint before the answer. Keep language age-appropriate. Return ONLY valid JSON with keys text, assessment, topic, student_state, delivery. assessment must be correct, partial, incorrect, or not_answer. student_state should be neutral, confident, uncertain, struggling, or frustrated. delivery should be normal, slow, or gentle.";
    $messages=[['role'=>'system','content'=>$system]];foreach(array_slice($history,-8) as$h)$messages[]=['role'=>$h['role']==='tutor'?'assistant':'user','content'=>$h['message']];$messages[]=['role'=>'user','content'=>(string)($b['message']??'')];
    $j=http_json('https://api.groq.com/openai/v1/chat/completions',['Authorization: Bearer '.$key,'Content-Type: application/json'],['model'=>$model,'messages'=>$messages,'temperature'=>0.35,'response_format'=>['type'=>'json_object']]);
    $content=$j['choices'][0]['message']['content']??'{}';$out=json_decode($content,true);if(!is_array($out))$out=['text'=>(string)$content];return['text'=>(string)($out['text']??''),'assessment'=>in_array($out['assessment']??'', ['correct','partial','incorrect','not_answer'],true)?$out['assessment']:'not_answer','topic'=>substr((string)($out['topic']??'General'),0,120),'student_state'=>(string)($out['student_state']??'neutral'),'delivery'=>(string)($out['delivery']??'normal'),'sources'=>[],'supplemental'=>false];
}
function tutor_history(string $session): array {$q=db()->prepare('SELECT role,message,created_at FROM tutor_messages WHERE session_id=? ORDER BY created_at DESC LIMIT 9');$q->execute([$session]);return array_reverse($q->fetchAll());}
function save_progress_assessment(string $sid,string $curr,string $subject,array $answer): void {$a=$answer['assessment']??'not_answer';if(!in_array($a,['correct','partial','incorrect'],true))return;$topic=substr(trim((string)($answer['topic']??'General')),0,120);$key=$curr.':'.$subject;$q=db()->prepare('SELECT * FROM student_progress WHERE student_id=? AND subject=? AND topic=? ORDER BY updated_at DESC LIMIT 1');$q->execute([$sid,$key,$topic]);$r=$q->fetch();$old=(int)($r['score']??0);$attempts=(int)($r['attempts']??0)+1;$delta=['correct'=>12,'partial'=>5,'incorrect'=>-3][$a];$score=max(0,min(100,$old+$delta));$status=$score>=80?'mastered':($score>=45?'developing':'started');if($r)db()->prepare('UPDATE student_progress SET score=?,attempts=?,status=?,updated_at=UTC_TIMESTAMP() WHERE id=?')->execute([$score,$attempts,$status,$r['id']]);else db()->prepare('INSERT INTO student_progress(id,student_id,subject,topic,score,attempts,status) VALUES(?,?,?,?,?,?,?)')->execute([uuid_v4(),$sid,$key,$topic,$score,$attempts,$status]);}
